version: "3"
services:
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - wordpress
    volumes:
      - ./src:/var/www/html
      - ./logs/nginx:/var/log/nginx
  wordpress:
    build: ./wordpress
    depends_on:
      - mariadb
    volumes:
      - ./src:/var/www/html
      - ./logs/wordpress/php:/var/log/php
  mariadb:
    build: ./mariadb
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: example
    volumes:
      - ./resources/mariadb:/var/lib/mysql
      - ./logs/mariadb:/var/log/mysql
