version: "3"
services:
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - wordpress
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx
  wordpress:
    build: ./wordpress
    volumes:
      - ./wordpress/src:/var/www/html
      - ./logs/wordpress/php:/var/log/php
